### ISSUE TITLE
Feature request: text template

### ISSUE THREAD

**Issue by pocomane** [aiq/luazdf#1]
I can not find any text-template function. Sorry if I missed it, however I attached a very simple exmple, in case you want to include it into the collection.

It use %b{} to separate verbatim text from template code. Then text and code are merged into a lua script and it is passed  to load(). It can:
- Mixing template statement and text
- Quick print the result of expressions

```
-- MIN-imal T-emplate

local function generate_mint(str, expansion_funcname)
  local script = ''
  str:gsub('(.-)@(%b{})', function(a,b)
    b = b:sub(2,#b-1)
    if b:match('^{.*}$') then
      b = b:sub(2,#b-1)
    else
      b = expansion_funcname..'(' .. b .. ')'
    end
    script = script .. expansion_funcname .. '(' .. string.format('%q', a) .. ') ' .. b .. ' '
  end)
  local verbatim_ending = str:match('^.*@%b{}(.-)$')
  if verbatim_ending then
    script = script .. expansion_funcname .. '(' .. string.format('%q', verbatim_ending) .. ')'
  end
  return script
end

local function mint(str, sandbox, expansion_funcname)
  if not expansion_funcname then expansion_funcname = 'o' end
  local script = generate_mint(str, expansion_funcname)
  print('EXAMPLE generated script:', script) -- todo : remove!
  local result = ''
   if 'table' ~= type(sandbox) then
    sandbox = {}
    for k,v in pairs(_ENV) do sandbox[k] = v end -- todo : better selection?
  end
  sandbox[expansion_funcname] = function(a) result = result .. a end
  load(script,'template','t', sandbox)()
  return result
end

-- Usage example
-- @{expression} will print the result of the lua expression
-- @{{statement}} let you to mix text and lua statement.
-- in statements you can use o() to output text

print(mint(
  "@{{for i=1,10 do}} hello @{item} @{{for j=1,2 do o'!' end}} \n@{{ end }} .", 
  {item='world'}
))
```

**Comment by aiq** [comment]
Currently has LuaZDF no template function. I wandet to implement something that works like the go template function[1].
But I can now safe the time, because your solution is really cool and works fine for me.

I would like to add this function to LuaZDF.
You can, if you find the time, add this function by yourself.
See http://luazdf.aiq.dk/contributing.html for more infos.

BR,
Alexander

[1] https://golang.org/pkg/html/template/

**Comment by aiq** [comment]
Hi,

I merged and modified[1] your function. Let me know if you are bothered with my modifications.

You can see the doc at https://luazdf.aiq.dk/fn/mint.html

Thanks!
Alexander

[1] https://github.com/aiq/luazdf/commit/1e585365e1ad3a4ff93618aa9c6651a7598a1c0b
